version: '3'
services:
  bot:
    build:
      context: .
      target: deploy
    restart: always
    environment:
      - BOT_TOKEN
      - APP_ID
      - FEEDBACK_WEBHOOK
      - OPEN_WEATHER_KEY
      - OWNER_ID
